### ISSUE TITLE
Compile hatası

### ISSUE THREAD

**Issue by AhmetErenArslan** [BuseDenizH/Develoading-MobileProject#5]
> npm run build

komutu çalıştırıldıgında proje compile olmuyor. hata veriyor.

Not building. Getting Error:
src/views/Tab2Page.vue:6:31 - error TS2339: Property 'goBack' does not exist on type 'CreateComponentPublicInstanceWithMixins<ToResolvedProps<{}, {}>, { IonContent: typeof IonContent; IonCol: typeof IonCol; IonGrid: typeof IonGrid; IonPage: typeof IonPage; IonRow: typeof IonRow; ... 9 more ...; handleClick: typeof handleClick; }, ... 23 more ..., {}>'.
6 <ion-button @click="goBack" class="back-button">

**Comment by tatabey** [comment]
Back button activated.
